// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZjcekvD7aXIeIFg5nhc431ZPNyZ37Sc',
    appId: '1:416866969773:android:02e70c3526ee5431f37e24',
    messagingSenderId: '416866969773',
    projectId: 'arpico-privilege',
    databaseURL: 'https://arpico-privilege.firebaseio.com',
    storageBucket: 'arpico-privilege.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4hQD4oagE9dQwvzt6jUB8MVhfNIHo42Y',
    appId: '1:416866969773:ios:92986f615556b506f37e24',
    messagingSenderId: '416866969773',
    projectId: 'arpico-privilege',
    databaseURL: 'https://arpico-privilege.firebaseio.com',
    storageBucket: 'arpico-privilege.firebasestorage.app',
    androidClientId: '416866969773-1lfemp176qoka0t84vcfdh7qm1novckh.apps.googleusercontent.com',
    iosClientId: '416866969773-pg5cio6dmj5gfegeobhveofcm3oi40ib.apps.googleusercontent.com',
    iosBundleId: 'com.arpico.groupit.arpicoprivilege',
  );
}
